name: Hikvision Doorbell
description: Connect your Hikvision doorbells to Home Assistant
version: '2.1'
slug: hikvision_doorbell
url: https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-sdk
arch:
- amd64
- i386
- aarch64
host_network: true
startup: application
boot: auto
stdin: true
homeassistant_api: true
hassio_api: true
options:
  ip: 192.168.0.70
  ip_indoor: 192.168.0.71
  username: admin
  password: password
  sensor_door: hikvision_door
  sensor_callstatus: hikvision_callstatus
  sensor_motion: hikvision_motion
  sensor_tamper: hikvision_tamper
  sensor_dismiss: hikvision_dismiss
  system:
    log_level: WARNING
schema:
  ip: str
  ip_indoor: str
  username: str
  password: str
  sensor_door: str
  sensor_callstatus: str
  sensor_motion: str
  sensor_tamper: str
  sensor_dismiss: str
  system:
    log_level: match(^ERROR|WARNING|INFO|DEBUG$)
